### ISSUE TITLE
Received this error: FileNotFoundError: [Errno 2] No such file or directory: './Output/Annotations.sqlite'

### ISSUE THREAD

**Issue by tttaaa000** [NIK4658/Apple-iBooks-Database-Exporter#1]
I tried to run the code via terminal 

python3 *filepath to downloaded DatabaseExporter.py file*

I received some lines generated but ended with the following error: 

**FileNotFoundError: [Errno 2] No such file or directory: './Output/Annotations.sqlite'**

I'm a noob, so I could be doing something wrong, but thought it would be fairly simple to run. Also nothing is in the Output folder. Thoughts?

**Comment by NIK4658** [comment]
Make sure the "Output" folder is present, and that it is **in the same path** as the "DatabaseExporter.py" file you downloaded. 

**Downloading only the "DatabaseExporter.py" file may cause this problem.**

Make sure the script is able to locate and copy the required files, the outcome of the operation is displayed in the console.
